apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: TEAM-NAME-postgresql
  namespace: default
spec:
  enableLogicalBackup: BACKUP
  teamId: TEAM
  volume:
    size: SIZE
  numberOfInstances: INSTANCES
  users:
    TEAM:  # database owner
    - superuser
    - createdb
  databases:
    DBNAME: TEAM
  postgresql:
    version: "14"
